// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kypvowwxewqkpcjcivbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5cHZvd3d4ZXdxa3BjamNpdmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTg1MjUsImV4cCI6MjA3Mzg3NDUyNX0.ciNSrdV1wq5dYJ2BX4cXjPEm0ciDLGGJTL81OnCDCM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});